version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/base:2020.11'
        auth:
         username: liorlieb7
         password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: |
          docker build -t spark:$CIRCLE_BUILD_NUM .
          docker run -d --name www -p 8090:8080 spark:$CIRCLE_BUILD_NUM
          sleep 7
          chmod +x ./httpcheck.sh
          ./httpcheck.sh
          docker tag spark:$CIRCLE_BUILD_NUM liorlieb7/spark:$CIRCLE_BUILD_NUM
          docker push liorlieb7/spark:$CIRCLE_BUILD_NUM
          
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
